"""Curriculum structure: stages, their lessons, and the steps inside a lesson.

Everything here is seeded content rather than user-authored - there is no
create/update API for it, only the browse endpoints in `router.py` and the
slug-keyed seed loader in `curriculum/`. That's why `slug`, not `id`, is the
identity of every row: a lesson's UUID is regenerated by a fresh database,
but its slug is stable across environments, which is what lets the seed
loader upsert content and what puts readable URLs in front of the student.

A lesson is an ordered list of `LessonStep`s rather than a body of text with
exercises attached. Reading, a multiple-choice check and a composition task
are the same kind of thing to the lesson player - one step you advance
through - so they're one table with a `kind` discriminator and a per-kind
`payload`, and a future step type is a new `kind` rather than a new table.

`position` is display order only, deliberately without a unique constraint:
the seed loader rewrites positions whenever content is reordered, and
uniqueness would make it fight itself mid-update for no benefit. Ties break
on slug so ordering stays deterministic either way.
"""

import enum
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class CourseLevel(str, enum.Enum):
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"


class StepKind(str, enum.Enum):
    """What a step asks of the student.

    `READING` is prose to absorb, `QUIZ` a multiple-choice check graded
    against a stored answer key, `COMPOSITION` a task the student answers by
    writing music that gets graded by the analysis engines.
    """

    READING = "reading"
    QUIZ = "quiz"
    COMPOSITION = "composition"


class LessonStatus(str, enum.Enum):
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"


class MasteryStatus(str, enum.Enum):
    """How well a student is doing on one topic.

    `UNTOUCHED` is never stored - a topic with no `TopicMastery` row is
    untouched by definition, and the skill map synthesises the status for
    every topic the student hasn't met yet. It's a member here so the API
    has one enum to describe all four states.
    """

    UNTOUCHED = "untouched"
    LEARNING = "learning"
    SOLID = "solid"
    NEEDS_PRACTICE = "needs_practice"


class Course(Base):
    """One stage of the roadmap - "Fundamentals", "Voice leading", ...

    Called a course rather than a stage because that's what it is from the
    student's side: a self-contained body of material with lessons and an
    exam. The roadmap is just every course in `position` order.
    """

    __tablename__ = "courses"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    slug: Mapped[str] = mapped_column(String(80), nullable=False, unique=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    level: Mapped[CourseLevel] = mapped_column(
        Enum(CourseLevel, name="course_level", values_callable=lambda e: [m.value for m in e]),
        nullable=False,
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class Lesson(Base):
    """One lesson within a course.

    `slug` is unique across every course, not just within one, so that moving
    a lesson to a different stage is a change of `course_id` alone and never
    breaks a bookmarked URL or an existing progress row.
    """

    __tablename__ = "lessons"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    course_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("courses.id", ondelete="CASCADE"), nullable=False, index=True
    )
    slug: Mapped[str] = mapped_column(String(80), nullable=False, unique=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    # One or two sentences for the roadmap card - what this lesson covers,
    # shown without having to open it.
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    position: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    estimated_minutes: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class Topic(Base):
    """One thing a student can be good or bad at.

    Topics are the axis the skill map is drawn on, and they're deliberately
    finer-grained than lessons: "parallel fifths and octaves" is a topic that
    a voice-leading lesson teaches, a counterpoint lesson leans on, and half
    a dozen composition tasks produce evidence about. Steps tag the topics
    they exercise (see `LessonStepTopic`), and mastery is accumulated per
    topic from every attempt that touched one.
    """

    __tablename__ = "topics"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    slug: Mapped[str] = mapped_column(String(80), nullable=False, unique=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    # Coarse grouping for the skill map's heatmap rows - "fundamentals",
    # "harmony", "counterpoint", "form". A string rather than an enum
    # because it's authored alongside the curriculum, and adding an area
    # shouldn't require a migration.
    area: Mapped[str] = mapped_column(String(64), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    position: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class LessonStep(Base):
    """One step of a lesson: something to read, answer, or compose.

    `payload` holds everything specific to the step's `kind` - the markdown
    for a reading, the question/choices/answer key for a quiz, the brief and
    requirement rules for a composition task. Its shape per kind is defined
    (and validated on the way out) by the discriminated union in
    `schemas.py`; keeping it as JSONB means authoring a new exercise is a
    content change, never a migration.
    """

    __tablename__ = "lesson_steps"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    lesson_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("lessons.id", ondelete="CASCADE"), nullable=False, index=True
    )
    slug: Mapped[str] = mapped_column(String(120), nullable=False, unique=True)
    kind: Mapped[StepKind] = mapped_column(
        Enum(StepKind, name="lesson_step_kind", values_callable=lambda e: [m.value for m in e]),
        nullable=False,
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class LessonStepTopic(Base):
    """Which topics a step exercises - many-to-many, both sides seeded.

    A composite primary key rather than a surrogate id: the pair *is* the
    row's identity, which is what lets the seed loader re-tag a step
    idempotently.
    """

    __tablename__ = "lesson_step_topics"

    step_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("lesson_steps.id", ondelete="CASCADE"),
        primary_key=True,
    )
    # Indexed on its own because the skill map reads the other direction -
    # "which steps exercise this topic" - and the composite primary key's
    # index only serves lookups that lead with `step_id`.
    topic_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("topics.id", ondelete="CASCADE"),
        primary_key=True,
        index=True,
    )


class StepAttempt(Base):
    """One attempt at one graded step, kept forever.

    Append-only, and deliberately so. Practice retries are unlimited and
    unpenalised, but every attempt is still evidence: the skill map reads
    this table to work out which topics a student keeps getting wrong, and
    overwriting a failed attempt with the eventual correct one would erase
    exactly the signal that makes the map worth having.

    The nullable columns are per-kind rather than universal - `is_correct`
    is a quiz's whole result, `score`/`passed` are a composition's - which is
    why none of them is required. `result` carries the detail the UI renders:
    the explanation for a quiz, the requirement checklist and analysis
    summary for a composition.
    """

    __tablename__ = "step_attempts"
    __table_args__ = (Index("ix_step_attempts_user_id_step_id", "user_id", "step_id"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    step_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("lesson_steps.id", ondelete="CASCADE"), nullable=False
    )
    # What the student submitted: `{"choice_index": 2}` for a quiz, the
    # notation document and its stored MusicXML key for a composition.
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)

    is_correct: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    # 0-100, and only ever advisory: a composition's *correctness* is
    # `passed` (every stated requirement met), which is decided by
    # deterministic rules, never by a score.
    score: Mapped[float | None] = mapped_column(Float, nullable=True)
    passed: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    result: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class UserProgress(Base):
    """Where a student has got to in one lesson.

    One row per `(user_id, lesson_id)`, created the moment the lesson is
    first opened - so the absence of a row means "not started", and a row
    with `completed_at` unset means "started, still going". That's a
    deliberate change from a table that only ever recorded completions: the
    roadmap needs to show what's underway, not just what's finished, and
    "continue where you left off" needs somewhere to remember the step.

    Nothing here gates anything. Every lesson is reachable regardless of
    progress; this table describes the student's path, it doesn't constrain
    it.
    """

    __tablename__ = "user_progress"
    __table_args__ = (UniqueConstraint("user_id", "lesson_id"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    lesson_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("lessons.id", ondelete="CASCADE"), nullable=False, index=True
    )
    status: Mapped[LessonStatus] = mapped_column(
        Enum(LessonStatus, name="lesson_status", values_callable=lambda e: [m.value for m in e]),
        nullable=False,
        default=LessonStatus.IN_PROGRESS,
    )
    # SET NULL rather than CASCADE: re-seeding a lesson replaces its steps,
    # and losing the bookmark should send the student back to the start of
    # that lesson, not delete their progress in it.
    current_step_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("lesson_steps.id", ondelete="SET NULL"), nullable=True
    )

    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class TopicMastery(Base):
    """How well one student is doing on one topic.

    Derivable from `StepAttempt` alone, and materialized anyway: the skill
    map's whole purpose is to answer "what am I good at, what needs work" at
    a glance, and doing that by aggregating every attempt a student has ever
    made - across topics, joined through the step-topic table - is a query
    that gets slower every week they use the site. This row is updated in
    the same transaction that records the attempt, so it can't drift.

    `recent_results` is what separates "struggled a year ago" from "getting
    it wrong now". A lifetime accuracy of 60% reads the same whether the
    student has just turned a corner or just started slipping, and the
    student wants to be told the second one. Capped at the last ten
    outcomes, oldest first.
    """

    __tablename__ = "topic_mastery"
    __table_args__ = (UniqueConstraint("user_id", "topic_id"),)

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    topic_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("topics.id", ondelete="CASCADE"), nullable=False, index=True
    )

    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    correct_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    # 0.0-1.0 over the student's whole history with this topic. Stored
    # rather than computed on read so the skill map can order by it.
    accuracy: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    recent_results: Mapped[list[bool]] = mapped_column(JSONB, nullable=False, default=list)

    status: Mapped[MasteryStatus] = mapped_column(
        Enum(MasteryStatus, name="mastery_status", values_callable=lambda e: [m.value for m in e]),
        nullable=False,
        default=MasteryStatus.LEARNING,
    )

    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )
