"""Curriculum structure: stages, their lessons, and the steps inside a lesson.

Everything here is seeded content rather than user-authored - there is no
create/update API for it, only the browse endpoints in `router.py` and the
slug-keyed seed loader in `curriculum/`. That's why `slug`, not `id`, is the
identity of every row: a lesson's UUID is regenerated by a fresh database,
but its slug is stable across environments, which is what lets the seed
loader upsert content and what puts readable URLs in front of the student.

A lesson is an ordered list of `LessonStep`s rather than a body of text with
exercises attached. Reading, a multiple-choice check and a composition task
are the same kind of thing to the lesson player - one step you advance
through - so they're one table with a `kind` discriminator and a per-kind
`payload`, and a future step type is a new `kind` rather than a new table.

`position` is display order only, deliberately without a unique constraint:
the seed loader rewrites positions whenever content is reordered, and
uniqueness would make it fight itself mid-update for no benefit. Ties break
on slug so ordering stays deterministic either way.
"""

import enum
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, Enum, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class CourseLevel(str, enum.Enum):
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"


class StepKind(str, enum.Enum):
    """What a step asks of the student.

    `READING` is prose to absorb, `QUIZ` a multiple-choice check graded
    against a stored answer key, `COMPOSITION` a task the student answers by
    writing music that gets graded by the analysis engines.
    """

    READING = "reading"
    QUIZ = "quiz"
    COMPOSITION = "composition"


class Course(Base):
    """One stage of the roadmap - "Fundamentals", "Voice leading", ...

    Called a course rather than a stage because that's what it is from the
    student's side: a self-contained body of material with lessons and an
    exam. The roadmap is just every course in `position` order.
    """

    __tablename__ = "courses"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    slug: Mapped[str] = mapped_column(String(80), nullable=False, unique=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    level: Mapped[CourseLevel] = mapped_column(
        Enum(CourseLevel, name="course_level", values_callable=lambda e: [m.value for m in e]),
        nullable=False,
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class Lesson(Base):
    """One lesson within a course.

    `slug` is unique across every course, not just within one, so that moving
    a lesson to a different stage is a change of `course_id` alone and never
    breaks a bookmarked URL or an existing progress row.
    """

    __tablename__ = "lessons"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    course_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("courses.id", ondelete="CASCADE"), nullable=False, index=True
    )
    slug: Mapped[str] = mapped_column(String(80), nullable=False, unique=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    # One or two sentences for the roadmap card - what this lesson covers,
    # shown without having to open it.
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    position: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    estimated_minutes: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class LessonStep(Base):
    """One step of a lesson: something to read, answer, or compose.

    `payload` holds everything specific to the step's `kind` - the markdown
    for a reading, the question/choices/answer key for a quiz, the brief and
    requirement rules for a composition task. Its shape per kind is defined
    (and validated on the way out) by the discriminated union in
    `schemas.py`; keeping it as JSONB means authoring a new exercise is a
    content change, never a migration.
    """

    __tablename__ = "lesson_steps"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    lesson_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("lessons.id", ondelete="CASCADE"), nullable=False, index=True
    )
    slug: Mapped[str] = mapped_column(String(120), nullable=False, unique=True)
    kind: Mapped[StepKind] = mapped_column(
        Enum(StepKind, name="lesson_step_kind", values_callable=lambda e: [m.value for m in e]),
        nullable=False,
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )
